### PR TITLE
Add exception classes.

### PR DESCRIPTION
**Pull request by richardhj**
Sister of metamodels/contao-frontend-editing#34

### CODE REVIEW

**Review by discordier — COMMENTED** [review]
I wonder if the exceptions would be better in main `dc-general` for usage in there as well?
I guess the Backend handling could also benefit from these.

What do you think?

Also ping @stefanheimes, @baumannsven

**Comment by richardhj** [comment]
A NotCreatableException already exists in dc-general, but no NotEditableException. FYI

**Comment by discordier** [comment]
Was looking for it in `2.1` and did not find it in `ContaoCommunityAlliance\DcGeneral\Exception\`...
I was not expecting it in `ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Exception\`
We also have a `NotDeletableException` sitting there.

This maybe should be generalized to top level exceptions and handled from backend and frontend.

So we need exceptions for:
- create
- edit
- delete

**Comment by richardhj** [comment]
So the new `ContaoCommunityAlliance\DcGeneral\Exception\NotEditableException` needs extend the `DcGeneralRuntimeException` and the `ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Exception\` needs to extend the `ContaoCommunityAlliance\DcGeneral\Exception\NotEditableException`.

**Comment by richardhj** [comment]
Ready to merge when contao-community-alliance/dc-general#482 is merged.

**Pull request merged**
